---
- name: Set Argo CD admin password (htpasswd, sense passlib)
  hosts: localhost
  connection: local
  gather_facts: false

  # Descomenta si uses Vault:
  vars_files:
    - "{{ playbook_dir }}/../group_vars/all/vault.yml"

  vars:
    argocd_namespace: argocd
    kubeconfig_local: "{{ lookup('env','HOME') + '/.kube/config' }}"

  pre_tasks:
    - name: Assert password present
      ansible.builtin.assert:
        that: (argocd_admin_password | default('')) | length > 0
        fail_msg: "Falta 'argocd_admin_password' (al Vault o via -e / ENV)."

  tasks:
    - name: Ensure apache2-utils (htpasswd) present
      become: true
      ansible.builtin.package:
        name: apache2-utils
        state: present

    - name: Locate htpasswd path
      ansible.builtin.shell: "which htpasswd"
      args:
        executable: /bin/bash
      register: htpasswd_path
      changed_when: false
      failed_when: htpasswd_path.rc != 0

    - name: Fail if htpasswd not found
      ansible.builtin.assert:
        that: htpasswd_path.rc == 0
        fail_msg: "'htpasswd' not found. Install 'apache2-utils'."


    - name: Generate bcrypt hash with htpasswd (stdin, no pipes)
      no_log: true
      ansible.builtin.command:
        argv:
          - "{{ htpasswd_path.stdout | trim }}"
          - -niB
          - -C
          - "10"
          - admin
      args:
        stdin: "{{ argocd_admin_password }}"
      register: ht_out
      changed_when: false

    - name: Extract bcrypt hash
      no_log: true
      ansible.builtin.set_fact:
        bcrypt_hash: "{{ (ht_out.stdout or '').split(':')[1] | trim }}"

    - name: Patch Argo CD admin secret
      #no_log: true
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_local }}"
        namespace: "{{ argocd_namespace }}"
        api_version: v1
        kind: Secret
        name: argocd-secret
        state: present
        definition:
          metadata: { name: argocd-secret }
          stringData:
            admin.password: "{{ bcrypt_hash }}"
            admin.passwordMtime: "{{ ansible_date_time.iso8601 }}"

    - name: Delete initial admin secret (opcional)
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_local }}"
        state: absent
        api_version: v1
        kind: Secret
        name: argocd-initial-admin-secret
        namespace: "{{ argocd_namespace }}"
      ignore_errors: true

    - name: Restart Argo CD server
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_local }}"
        api_version: apps/v1
        kind: Deployment
        name: argo-cd-argocd-server
        namespace: "{{ argocd_namespace }}"
        state: present
        wait: true
        wait_timeout: 180
        force: true

    - name: Done
      ansible.builtin.debug:
        msg: "✅ Contrasenya d'admin d'Argo CD actualitzada."
